=== CsikosMate/SLDHOOWebXML/SLDHOO_1007/SLDHOO_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hallgato" type="hallgatoTipus"/>
                <xs:element name="kurzusok" type="kurzusokTipus"/>
            </xs:sequence>
            <xs:attribute name="tanev" type="xs:string"/>
            <xs:attribute name="egyetem" type="egyetemTipus"/>
        </xs:complexType>
        <xs:key name="hallgatoKulcs">
            <xs:selector xpath="hallgato"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
        <xs:key name="kurzusKulcs">
            <xs:selector xpath="kurzusok/kurzus"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
    </xs:element>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ME"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="hallgatoTipus">
        <xs:sequence>
            <xs:element name="hnev" type="xs:string"/>
            <xs:element name="szulev" type="xs:positiveInteger"/>
            <xs:element name="szak" type="szakTipus"/>
        </xs:sequence>
        <xs:attribute name="id" type="idTipus"/>
    </xs:complexType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:length value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="szakTipus">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="evf" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="kurzusokTipus">
        <xs:sequence>
            <xs:element name="kurzus" type="kurzusTipus" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kurzusTipus">
        <xs:sequence>
            <xs:element name="kurzusnev" type="xs:string"/>
            <xs:element name="kredit" type="xs:positiveInteger"/>
            <xs:element name="hely" type="xs:string"/>
            <xs:element name="idopont" type="xs:string"/>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="oktato" type="xs:string"/>
                <xs:element name="oraado" type="xs:string"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="jovahagyas" type="igenNemTipus" use="optional"/>
        <xs:attribute name="nyelv" type="nyelvTipus" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nyelvTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="magyar"/>
            <xs:enumeration value="angol"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== CsikosMate/SLDHOOWebXML/SLDHOO_1007/SLDHOO_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<kurzusfelvetel tanev="2026_2027 I." egyetem="ME" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="SLDHOO_kurzusfelvetel.xsd">
    <hallgato id="SLDHOO">
        <hnev>Csikos Máté</hnev>
        <szulev>2005</szulev>
        <szak evf="3">Mérnökinformatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL32K-B2">
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Szerda 12:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAL331-B2">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Hétfő 14:00-15:30</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEVEE050-B2" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Elektrotechnika-elektronika</kurzusnev>
            <kredit>5</kredit>
            <hely>III. előado</hely>
            <idopont>Hétfő 8:00-9:30</idopont>
            <oktato>Szabó Norbert</oktato>
            <oraado>Szabó Norbert</oraado>
        </kurzus>
        <kurzus id="GEIAK130-B2" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXIII. előado</hely>
            <idopont>Kedd 8:00-9:30</idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
            <oraado>Fazekas Levente</oraado>
        </kurzus>
        <kurzus id="GEIAL335-B2" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Hétfő 16:00-17:30</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
    </kurzusok>
</kurzusfelvetel>
